# loan-calculator-form
provider:
  name: faas
  gateway: http://127.0.0.1:31112
functions:
  loan-calculator-form:
    lang: node
    handler: ./loan-calculator-form
    image: padiazg/loan-calculator-form:latest
